radio.onReceivedNumber(function (receivedNumber) {
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.SignalStrength)))
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.Time)))
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.SerialNumber)))
    basic.showString("" + (receivedNumber))
    radio.sendNumber(receivedNumber)
})
radio.onReceivedString(function (receivedString) {
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.SignalStrength)))
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.Time)))
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.SerialNumber)))
    basic.showString(receivedString)
    radio.sendString(receivedString)
})
radio.onReceivedValue(function (name, value) {
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.SignalStrength)))
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.Time)))
    basic.showString("" + (radio.receivedPacket(RadioPacketProperty.SerialNumber)))
    basic.showString(name)
    basic.showString("" + (value))
    radio.sendValue(name, value)
})
